# Generated by Django 2.1.2 on 2019-03-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
        migrations.RemoveField(
            model_name='site',
            name='day',
        ),
        migrations.RemoveField(
            model_name='site',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sequence',
        ),
        migrations.AddField(
            model_name='schedule',
            name='sequence',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
