# Generated by Django 2.1.2 on 2019-03-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20190313_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
